---
title: "Arm"
author: "Ana Palacio-Castro"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    fig_height: 8
    fig_width: 8
    df_print: paged
    toc: yes
    toc_float: true
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
  knitr::opts_chunk$set(warning = FALSE, 
                        message = FALSE,
                        #options(knitr.kable.NA = ''),
                        fig.align = "center")
```

# Libraries and settings

```{r, include=FALSE}
# Libraries
    library(plyr)
    library(tidyverse)
    library(reshape2)
    library(lubridate)
    library(knitr)
    library(dplyr)
    library(broom)

    library(ggpubr)
    library(ggthemes)
    library(gridExtra)
    library(ggExtra)
    
#Models     
    library(lmerTest)
    library(emmeans)

# Interactive Maps
    library(leaflet)
```

# Import and format data

```{r}
Import_Arm<- function (dir)  {
  
# 1. Read all the .csv files (; delimited) and consolidate them in a single data frame
  # dir: folder containing the .csv files. The data in the dir can be separated in subfolders, 
  # recursive = TRUE will find the .csv files inside the subfolders
  # You can use the subfolders names to later extract information with the option full.names=TRUE
  
  Arm.data<-plyr::ldply (list.files(path=dir, pattern="*.csv", 
                                full.names=TRUE, recursive = TRUE),
                     function(filename) {
                       dum=(read.csv(filename, sep = ",", blank.lines.skip=T))
                       dum$filename=filename
                       return(dum)
                     })
}

Duration<-Import_Arm("Data")


Duration_name <- plyr::rbind.fill(lapply(strsplit(as.character(Duration$filename), split="/"), 
                                    function(X) data.frame(t(X))))

Duration$created_at[] <- lapply(Duration$created_at, gsub, pattern="-04:00", replacement="")
Duration$created_at[] <- lapply(Duration$created_at, gsub, pattern="T", replacement=" ")

# Date_time <- plyr::rbind.fill(lapply(strsplit(as.character(Duration$created_at), split="T"), 
#                                     function(X) data.frame(t(X))))

Duration <- cbind(Duration_name[,-1], Duration[,-10])

head(Duration)
colnames(Duration) <- c("Arm", "File", "DateTime", "entry_id", "beaker", "duration", "errors", "latitude",  "longitude",  "elevation", "status")

# Remove duplicate rows
Duration$ID<-paste0(Duration$Arm, Duration$DateTime)
Duration <- Duration[!duplicated(Duration$ID), ]
#Duration<-Duration[!(Duration$duration<3),]


```


```{r, include=FALSE}

Duration$Arm<-as.factor(Duration$Arm)
Duration$beaker<-as.factor(Duration$beaker)
Duration$DateTime<-as.character(Duration$DateTime)
Duration$Date<-as.Date(Duration$DateTime)
Duration$Date_Time<-as.POSIXct(Duration$DateTime)

summary(Duration)
```

# All data

```{r}

# All_data<- ggplot(Duration) + 
#   
#   theme_bw() +
#   # scale_x_continuous(limits = c(0, 24),
#   #                     expand = c(0.01, 0.01),
#   #                     breaks = seq(0, 24, 2),
#   #                     name="Time of the day")+
#   geom_point(aes(Date_Time, duration, colour=Arm))+
#   facet_wrap(~beaker)
# All_data

```

# Current data

```{r}
Current<-Duration[Duration$Date>"2023-05-02", ]
```

```{r}
Cases.Armand<-Current[Current$Arm=="Armand", ] %>% count(beaker,
                                  sort = F)

Cases.Armanda<-Current[Current$Arm=="Armanda", ] %>% count(beaker,
                                  sort = F)

Cases<-cbind(Cases.Armand, Cases.Armanda[,-1 ])
colnames(Cases) <-c("Beaker", "Armand", "Armanda")

kable(as.data.frame(Cases, format = "markdown"), 
      longtable = TRUE)
```

```{r}

Current_data<- ggplot(Current) + 
  
  theme_bw() +
  # scale_x_continuous(limits = c(0, 24),
  #                     expand = c(0.01, 0.01),
  #                     breaks = seq(0, 24, 2),
  #                     name="Time of the day")+
  geom_point(aes(Date_Time, duration, fill=Arm), shape=21, size=0.6)+
  facet_wrap(~beaker)
Current_data

```

```{r, echo=FALSE}

mean.beaker <- ddply (Current, .(beaker, Arm, Date), summarise,
                D_mean = mean (duration, na.rm = T),
                D_sd = sd (duration, na.rm = T),
                number = n())
mean.beaker

mean.beaker <- ddply (Current, .(beaker, Arm),summarise,
                D_mean = mean (duration, na.rm = T),
                D_sd = sd (duration, na.rm = T),
                number = n())
mean.beaker

mean.round <- ddply (mean.beaker, .(Arm),summarise,
                R_mean = mean (D_mean, na.rm = T),
                R_sd = sd (D_mean, na.rm = T),
                number = n())

mean.round$round.min<-as.character(round((mean.round$R_mean*mean.round$number)/60, 2))
mean.round
mean.round$round.min
```

```{r}
Minutes_round<- ggplot(Current, aes(beaker, duration, fill=Arm)) + 
  
  theme_bw() +
  # scale_x_continuous(limits = c(0, 24),
  #                     expand = c(0.01, 0.01),
  #                     breaks = seq(0, 24, 2),
  #                     name="Time of the day")+
  geom_jitter(aes(colour=Arm), size=1, alpha=0.5)+
  stat_summary(fun.data = "mean_cl_boot", aes(fill=Arm), shape=21)
  # annotate(geom="text", x = 12, y = 1, parse=TRUE,
  #              label =paste0("Armand (min) ",mean.round$round.min[1], size=4))+
  #  annotate(geom="text", x = 36, y = 1, parse=TRUE,
  #              label =paste0("Armanda (min) ",mean.round$round.min[2], size=4))

Minutes_round
Minutes_round + facet_wrap(~Date)
```
